# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: SSH@0
  inputs:
    runOptions: 'commands'
    commands: 'curl https://sdk.cloud.google.com | bash'
    readyTimeout: '20000'
- task: SSH@0
  inputs:
    runOptions: 'commands'
    commands: 'gcloud auth login'
    readyTimeout: '20000'
- task: SSH@0
  inputs:
    runOptions: 'commands'
    commands: 'gcloud builds submit --tag gcr.io/[pcigcp-369509]/[my-app-v1]'
    readyTimeout: '20000'
- task: SSH@0
  inputs:
    runOptions: 'commands'
    commands: 'gcloud run deploy --image gcr.io/pcigcp-369509]/[my-app-v1] --platform managed'
    readyTimeout: '20000'